name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Checkstyle
      run: |
        ./gradlew checkstyleMain
    - name: PMD
      run: |
        ./gradlew pmdMain